# Generated by Django 5.1.3 on 2024-11-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockVisualizer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="symbol",
            new_name="from_symbol",
        ),
        migrations.AddField(
            model_name="stockdata",
            name="to_symbol",
            field=models.TextField(null=True),
        ),
    ]
